import {importQuestions,get,put,all,openDB,saveSetting,runQuestionBankFixMigration} from './db.js';
import {today,getOrCreateToday,questionsFor,enabledPoints} from './questionEngine.js';
import {score} from './scoring.js';
import {recordWrong,recordReviewCorrect} from './wrongQuestions.js';
import {updateKnowledge} from './statistics.js';
import {formatMath,normalizeMathInput,displayClass} from './formatMath.js';
import {initPwaUpdates} from './updateManager.js';
import {initialAttemptPolicy,currentFirstCorrect as firstAttemptState,summarizeFirstAttempts,nextAttemptCount} from './attemptPolicy.js';

const app=document.querySelector('#app');let task,questions,date,activeMathInput=null,lastMathSelection=0,timerId,actionBusy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qAnswer=q=>Array.isArray(q.answer)?q.answer.join('；'):q.answer;
/* Display-only compatibility recheck for records created before harmless format normalization. It never rewrites history or statistics. */
const currentFirstCorrect=(q,r)=>firstAttemptState(q,r,(question,values)=>score(question,values).correct===true);
const answers=async()=> (await all('answers')).filter(x=>x.date===date);
const record=q=>get('answers',`${date}:${q.id}`);
const isInitialSubmitted=r=>Boolean(r?.initialSubmitted||r?.resolved||r?.firstAttemptCorrect!==undefined||r?.firstAnswer!==undefined);
const needsCorrection=r=>isInitialSubmitted(r)&&(r?.firstAttemptCorrect===null||(r?.firstAttemptCorrect===false&&!r.resolved));
const isFinalStage=()=>['review','correction','complete'].includes(task.phase);
const duration=ms=>{const s=Math.max(0,Math.floor(ms/1000)),m=Math.floor(s/60);return `${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const previousDate=date=>new Date(Date.UTC(...date.split('-').map((value,index)=>Number(value)-(index===1?1:0)))-86400000).toISOString().slice(0,10);
const checkinStreak=(checkins,from=date)=>{const dates=new Set(checkins.map(item=>item.date));let cursor=from,total=0;while(dates.has(cursor)){total++;cursor=previousDate(cursor)}return total};
function shell(html){clearInterval(timerId);timerId=null;app.innerHTML=`<div class="shell">${html}</div>`}
async function saveTask(){await put('dailyTasks',task)}
function startTimer(){const el=document.querySelector('#timer');if(!el||!task.startedAt||task.endedAt)return;const update=()=>el.textContent=`用时 ${duration(Date.now()-task.startedAt)}`;update();timerId=setInterval(update,1000)}
function inputsFor(q,old){const count=q.answerType==='multiple_blank'?(Array.isArray(q.answer)?q.answer.length:1):1;return Array.from({length:count},(_,i)=>`<input data-answer="${i}" inputmode="text" autocomplete="off" value="${esc(old?.currentInputs?.[i]||'')}" placeholder="答案${count>1?` ${i+1}`:''}">`).join('')}
function questionNav(index){return `<nav class="question-nav" aria-label="题目跳转">${questions.map((_,i)=>`<button type="button" data-go="${i}" class="${i===index?'active':''}" aria-current="${i===index?'step':'false'}">${i+1}</button>`).join('')}</nav>`}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function settledValues(){const inputs=[...document.querySelectorAll('[data-answer]')],deadline=Date.now()+900;while(Date.now()<deadline){const composing=inputs.some(input=>input.dataset.composing==='true'),latest=Math.max(0,...inputs.map(input=>Number(input.dataset.lastInputAt||0)));if(!composing&&Date.now()-latest>=120)break;await wait(25)}await wait(16);return inputs.map(input=>input.value.trim())}
function setActionDisabled(disabled){document.querySelectorAll('button').forEach(button=>button.disabled=disabled)}
async function once(action){if(actionBusy)return;actionBusy=true;setActionDisabled(true);try{return await action()}finally{actionBusy=false;setActionDisabled(false)}}

async function home(){const rs=await answers(),drafts=rs.filter(r=>r.draftSaved).length,checkins=await all('checkins');const focus=[...new Set(questions.map(q=>q.knowledgePoint))].slice(0,3).join('、');const correcting=rs.filter(needsCorrection).length;const completed=task.phase==='complete';const label=completed?'查看今日结果':isFinalStage()?(task.phase==='correction'?`继续订正（${correcting}题）`:'查看统一答案'):task.startedAt?'继续今日训练':'开始今日训练';shell(`<section class="card"><p class="eyebrow">七年级数学</p><h1 class="title">每日计算打卡</h1><p class="subtle">${date} · 基础诊断模式</p><div class="home-grid"><div class="metric">连续打卡<b>${checkinStreak(checkins)} 天</b></div><div class="metric">今日暂存<b>${isFinalStage()?'10':drafts} / 10</b></div><div class="metric">预计用时<b>8-10 分钟</b></div></div><p class="focus">今日重点：${esc(focus)}</p><button class="primary-wide" id="start">${label}</button><div class="actions"><button class="secondary" id="settings">学习范围设置</button><button class="secondary" id="parent">家长统计</button></div></section>`);document.querySelector('#start').onclick=()=>once(async()=>{if(completed)return resultPage();if(isFinalStage())return task.phase==='correction'?correctionPage():reviewPage();if(!task.startedAt){task.startedAt=Date.now();await saveTask()}return questionPage(Number(task.currentIndex||0))});document.querySelector('#settings').onclick=settingsPage;document.querySelector('#parent').onclick=()=>location.href='./parent.html';}
function toolKeys(q){const basic=['+','−','×','÷','/','(',')'];return q.answerType==='number'?basic:[...basic,'|','²','³','^']}
function inputTools(q){return `<div class="math-tools">${toolKeys(q).map(k=>`<button type="button" data-key="${k}">${k}</button>`).join('')}</div>`}
function bindTools(){const inputs=[...document.querySelectorAll('[data-answer]')];const remember=e=>{activeMathInput=e.currentTarget;lastMathSelection=activeMathInput.selectionStart??activeMathInput.value.length;};inputs.forEach(input=>{['focus','click','keyup','select'].forEach(event=>input.addEventListener(event,remember));input.addEventListener('input',event=>{input.dataset.lastInputAt=String(Date.now());remember(event)});input.addEventListener('compositionstart',()=>input.dataset.composing='true');input.addEventListener('compositionend',event=>{input.dataset.composing='false';input.dataset.lastInputAt=String(Date.now());remember(event)})});document.querySelectorAll('[data-key]').forEach(button=>{const keepInputFocus=e=>e.preventDefault();button.addEventListener('pointerdown',keepInputFocus);button.addEventListener('mousedown',keepInputFocus);button.addEventListener('click',()=>{const input=activeMathInput&&document.contains(activeMathInput)?activeMathInput:inputs[0];if(!input)return;const start=input.selectionStart??lastMathSelection??input.value.length,end=input.selectionEnd??start,key=button.dataset.key;input.value=input.value.slice(0,start)+key+input.value.slice(end);const cursor=start+key.length;input.focus({preventScroll:true});input.setSelectionRange(cursor,cursor);lastMathSelection=cursor;input.dispatchEvent(new Event('input',{bubbles:true}));});});}
async function save(q,r){r.key=`${date}:${q.id}`;r.date=date;r.questionId=q.id;await put('answers',r)}

async function questionPage(index){const q=questions[index],old=await record(q)||{};task.currentIndex=index;await saveTask();shell(`<section class="card question-card"><div class="topline"><span>第 ${index+1} / 10 题</span><span id="timer" class="tag"></span></div><div class="progress"><i style="width:${(index+1)/10*100}%"></i></div>${questionNav(index)}<span class="tag">${esc(q.knowledgePoint)}</span><div class="question ${displayClass(q.question)}">${formatMath(q.displayQuestion||q.question)}</div><div class="answer-area">${inputsFor(q,old)}</div>${inputTools(q)}<p class="subtle small">答案仅暂存；可直接选择任意题目回看，最后统一提交判分。</p><div class="actions">${index?'<button class="secondary" id="prev">上一题</button>':''}<button id="next">${index===9?'完成答题，检查并提交':'暂存并下一题'}</button><button class="warning" id="giveup">不会，暂时留空</button></div></section>`);startTimer();bindTools();document.querySelector('#next').onclick=()=>prepareDraft(q,index,false);document.querySelector('#giveup').onclick=()=>prepareDraft(q,index,true);document.querySelector('#prev')?.addEventListener('click',()=>prepareDraft(q,index,false,index-1));document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>{const destination=Number(button.dataset.go);if(destination!==index)prepareDraft(q,index,false,destination)});}
function prepareDraft(q,index,giveUp,target){return once(async()=>{if(giveUp)return saveDraft(q,index,[],true,target);const values=await settledValues(),destination=target??(index===9?null:index+1),label=destination===null?'确认暂存并检查':destination<index?'确认暂存并返回上一题':'确认暂存并下一题';confirmSubmit(values,()=>saveDraft(q,index,values,false,target),()=>saveDraft(q,index,values,false,index),label)})}
function confirmSubmit(values,onConfirm,onEdit,label='确认暂存'){const read=values.map(normalizeMathInput).join('；'),area=document.querySelector('.actions');area.innerHTML=`<div class="answer-key">系统读取为：${formatMath(read)}</div><button id="confirm">${esc(label)}</button><button class="secondary" id="edit">继续修改</button>`;document.querySelector('#confirm').onclick=()=>once(onConfirm);document.querySelector('#edit').onclick=()=>once(onEdit)}
async function saveDraft(q,index,values,gaveUp,target){const r=await record(q)||{startTime:Date.now()};r.currentInputs=values;r.draftSaved=true;r.gaveUp=gaveUp||values.every(v=>!v);r.feedback=null;await save(q,r);const destination=target??(index===9?null:index+1);return destination===null?finalCheckPage():questionPage(destination)}
async function finalCheckPage(){const rs=await answers(),drafts=rs.filter(r=>r.draftSaved).length,blank=questions.filter(q=>{const r=rs.find(x=>x.questionId===q.id);return !r?.currentInputs?.some(Boolean)}).length;shell(`<section class="card result"><p class="eyebrow">最终检查</p><h1 class="title">${drafts} / 10 题已暂存</h1><p class="subtle">现在仍可直接选择任意题修改答案。点击“全部提交”后，计时停止，并统一显示每题对错、标准答案和订正入口。</p>${questionNav(-1)}<div class="home-grid"><div class="metric">已填写<b>${10-blank} 题</b></div><div class="metric">暂时留空<b>${blank} 题</b></div><div class="metric">当前用时<b id="timer"></b></div></div><div class="actions"><button class="secondary" id="back">返回第 10 题</button><button id="final-submit">全部提交并查看结果</button></div></section>`);startTimer();document.querySelector('#back').onclick=()=>once(()=>questionPage(9));document.querySelectorAll('[data-go]').forEach(button=>button.onclick=()=>once(()=>questionPage(Number(button.dataset.go))));document.querySelector('#final-submit').onclick=()=>once(finalSubmit);}
async function writeCheckin(records){const existing=await get('checkins',date),first=records.filter(record=>record.firstAttemptCorrect===true).length,wrong=records.filter(record=>record.firstAttemptCorrect===false).length,manual=records.filter(record=>record.firstAttemptCorrect===null).length;await put('checkins',{...existing,date,completedAt:existing?.completedAt||task.endedAt||Date.now(),firstCorrect:first,wrong,manual,corrected:records.filter(record=>record.corrected).length})}
async function restoreSubmittedCheckin(){if(!isFinalStage()||await get('checkins',date))return;const records=await answers();if(records.length===questions.length&&records.every(isInitialSubmitted))await writeCheckin(records)}
async function finalSubmit(){task.phase='submitting';task.endedAt=Date.now();await saveTask();const submitted=[];for(const q of questions){let r=await record(q)||{currentInputs:[],draftSaved:true,gaveUp:true,startTime:task.startedAt};const source=task.items?.find(x=>x.questionId===q.id)?.sourceType;const values=r.currentInputs||[];const verdict=r.gaveUp||!values.some(Boolean)?{correct:false}:{...score(q,values)},policy=initialAttemptPolicy(verdict);r.attemptCount=1;r.initialSubmitted=true;r.firstAnswer=values;r.manualCheck=Boolean(verdict.manualCheck);r.firstAttemptCorrect=policy.firstAttemptCorrect;r.resolved=policy.resolved;r.endTime=r.resolved?task.endedAt:null;if(policy.countsForStatistics){if(policy.recordsWrongQuestion){r.firstWrongRecorded=true;await recordWrong(q.id,date)}else if(source==='wrong_review')await recordReviewCorrect(q.id);await updateKnowledge(q,date,r.firstAttemptCorrect);}await save(q,r);submitted.push(r)}await writeCheckin(submitted);task.phase='review';await saveTask();return reviewPage()}

async function reviewPage(){const rs=await answers(),byId=new Map(rs.map(r=>[r.questionId,r])),wrong=rs.filter(needsCorrection).length;shell(`<section class="card result"><p class="eyebrow">统一答案与订正</p><h1 class="title">已完成 10 / 10 题</h1><p class="subtle">以下保留首次作答、标准答案与订正状态，方便复盘。</p><div class="answer-list">${questions.map((q,i)=>{const r=byId.get(q.id),firstState=currentFirstCorrect(q,r),pending=firstState===null,correct=firstState===true,rechecked=r?.firstAttemptCorrect===undefined&&correct,status=pending?'系统暂时无法可靠判断该题':correct?(rechecked?'首次作答：正确（按现行格式规则重新识别）':'首次作答：正确'):r?.corrected?'首次作答：不正确，已订正':'首次作答：不正确',note=pending?'请重新输入或由家长确认。':correct?'':r?.corrected?'已完成订正':'需要订正',firstAnswer=(r?.firstAnswer||[]).filter(Boolean).join('；')||'不会 / 未作答';return `<article class="answer-key"><b>第 ${i+1} 题</b><div class="question small ${displayClass(q.question)}">${formatMath(q.displayQuestion||q.question)}</div><div>${status}</div><div class="${correct||pending?'student-answer':'student-answer wrong-answer'}">你的首次答案：${formatMath(firstAnswer)}</div><div class="standard-answer">标准答案：${formatMath(qAnswer(q))}</div>${note?`<div class="small">${note}</div>`:''}</article>`}).join('')}</div><div class="actions"><button id="correct">${wrong?`开始订正（${wrong}题）`:'返回完成页'}</button><button class="secondary" id="back">返回首页</button></div></section>`);document.querySelector('#correct').onclick=async()=>{if(!wrong)return resultPage();task.phase='correction';await saveTask();correctionPage()};document.querySelector('#back').onclick=home;}
async function correctionPage(){const rs=await answers(),r=rs.find(needsCorrection);if(!r)return finalize();const q=questions.find(x=>x.id===r.questionId),showAnswer=Boolean(r.feedback?.showAnswer),feedback=r.feedback?.kind==='correction'?`<div class="feedback bad">${esc(r.feedback.text)}</div>`:'',inputRecord={...r,currentInputs:r.correctionInputs||[]};let subtitle='请重新计算后提交；首次订正不会显示标准答案。',manualUI='';if(r.manualCheck&&r.firstAttemptCorrect===null){subtitle='系统暂时无法可靠判断这个答案，请检查输入格式后重新提交。';manualUI=`<div class="actions" style="margin-top:1rem;padding-top:1rem;border-top:1px dashed #ccc;"><p class="small" style="width:100%">系统无法判分，也可由家长协助判定：</p><button class="secondary" id="parent-correct">判为正确</button><button class="secondary" id="parent-wrong">判为错误</button></div>`;}shell(`<section class="card question-card"><div class="topline"><span>订正 ${rs.filter(needsCorrection).length} 题</span><span class="tag">${esc(q.knowledgePoint)}</span></div><div class="question ${displayClass(q.question)}">${formatMath(q.displayQuestion||q.question)}</div><p class="subtle">${subtitle}</p>${showAnswer?`<div class="answer-key">标准答案：${formatMath(qAnswer(q))}</div>`:''}<div class="answer-area">${inputsFor(q,inputRecord)}</div>${inputTools(q)}${feedback}<div class="actions"><button id="submit">${r.manualCheck&&r.firstAttemptCorrect===null?'重新输入':'提交订正'}</button><button class="secondary" id="back">返回统一答案</button></div>${manualUI}</section>`);bindTools();document.querySelector('#submit').onclick=()=>prepareCorrectionSubmit(q,r);document.querySelector('#back').onclick=reviewPage;if(r.manualCheck&&r.firstAttemptCorrect===null){document.querySelector('#parent-correct').onclick=()=>once(async()=>{r.manualCheck=false;r.firstAttemptCorrect=true;r.resolved=true;r.endTime=Date.now();r.feedback=null;const source=task.items?.find(x=>x.questionId===q.id)?.sourceType;if(source==='wrong_review')await recordReviewCorrect(q.id);await updateKnowledge(q,date,true);await save(q,r);return correctionPage();});document.querySelector('#parent-wrong').onclick=()=>once(async()=>{r.manualCheck=false;r.firstAttemptCorrect=false;r.resolved=false;r.firstWrongRecorded=true;r.feedback=null;await recordWrong(q.id,date);await updateKnowledge(q,date,false);await save(q,r);return correctionPage();});}}
function prepareCorrectionSubmit(q,r){return once(async()=>{const values=await settledValues();confirmSubmit(values,()=>correctionSubmit(q,r,values),async()=>{r.correctionInputs=values;await save(q,r);return correctionPage()},'确认提交订正')})}
async function correctionSubmit(q,r,values){r.correctionInputs=values;const verdict=score(q,values);if(r.manualCheck&&r.firstAttemptCorrect===null){r.attemptCount=nextAttemptCount(r.attemptCount);r.firstAnswer=values;if(verdict.manualCheck){r.feedback={kind:'correction',showAnswer:false,text:'输入仍无法解析，请检查格式或由家长判定。'};}else{const policy=initialAttemptPolicy(verdict);r.manualCheck=false;r.firstAttemptCorrect=policy.firstAttemptCorrect;r.resolved=policy.resolved;r.endTime=r.resolved?Date.now():null;if(policy.recordsWrongQuestion){r.firstWrongRecorded=true;await recordWrong(q.id,date);}else if(r.firstAttemptCorrect===true){const source=task.items?.find(x=>x.questionId===q.id)?.sourceType;if(source==='wrong_review')await recordReviewCorrect(q.id);}if(policy.countsForStatistics)await updateKnowledge(q,date,r.firstAttemptCorrect);r.feedback=null;}await save(q,r);return correctionPage();}r.attemptCount=nextAttemptCount(r.attemptCount);if(verdict.correct){r.finalAnswer=values;r.corrected=true;r.resolved=true;r.endTime=Date.now();r.feedback=null}else r.feedback={kind:'correction',showAnswer:true,text:verdict.manualCheck?'输入无法可靠解析，请对照标准答案检查后再修改。':'仍不正确，标准答案已显示，请检查符号、括号或分数。'};await save(q,r);return correctionPage()}
async function finalize(){const rs=await answers();if(rs.some(needsCorrection))return correctionPage();await writeCheckin(rs);task.phase='complete';await saveTask();return resultPage()}
async function resultPage(){const rs=await answers(),states=rs.map(r=>currentFirstCorrect(questions.find(q=>q.id===r.questionId),r)),summary=summarizeFirstAttempts(states),corrected=rs.filter(x=>x.corrected).length,firstWrong=rs.filter(r=>currentFirstCorrect(questions.find(q=>q.id===r.questionId),r)===false),manualPending=summary.pending,correctionPending=rs.filter(needsCorrection).length,accuracy=summary.accuracy===null?'暂无可统计数据':`${Math.round(summary.accuracy*100)}%`;const weak={},sources={weakness:0,review:0,wrong_review:0};for(const r of firstWrong){const q=questions.find(x=>x.id===r.questionId);weak[q.knowledgePoint]=(weak[q.knowledgePoint]||0)+1}for(const item of(task.items||[]))sources[item.sourceType]=(sources[item.sourceType]||0)+1;shell(`<section class="card result"><p class="eyebrow">今日完成</p><h1 class="title">10 / 10</h1><p class="subtle">总用时：${task.startedAt&&task.endedAt?duration(task.endedAt-task.startedAt):'—'}</p><div class="home-grid"><div class="metric">首次正确<b>${summary.correct} / ${summary.determined}</b></div><div class="metric">首次正确率<b>${accuracy}</b></div><div class="metric">已订正<b>${corrected} 题</b></div></div>${manualPending?`<p class="focus">待确认 ${manualPending} 题</p>`:''}${firstWrong.length?`<section class="answer-key"><b>首次作答需要复习：${firstWrong.length} 题</b>${firstWrong.map(r=>{const q=questions.find(x=>x.id===r.questionId),number=questions.indexOf(q)+1,yourAnswer=(r.firstAnswer||[]).filter(Boolean).join('；')||'不会 / 未作答';return `<div class="small">第 ${number} 题 · ${esc(q.knowledgePoint)} · ${r.corrected?'已订正':'待订正'}<br><span class="wrong-answer">你的首次答案：${formatMath(yourAnswer)}</span><br><span class="standard-answer">标准答案：${formatMath(qAnswer(q))}</span></div>`}).join('')}</section>`:'<p class="focus">本次没有已判定的首次错误。</p>'}<p class="subtle">今日训练构成：弱项强化 ${sources.weakness||0} 题 · 普通复习 ${sources.review||0} 题 · 错题回炉 ${sources.wrong_review||0} 题</p><p class="focus">今天需要多复习：${esc(Object.keys(weak).join('、')||'今天的基础很扎实')}</p><div class="actions">${correctionPending?'<button id="correct">继续订正/确认</button>':''}<button class="secondary" id="details">查看逐题结果</button><button class="secondary" id="back">返回首页</button></div></section>`);document.querySelector('#correct')?.addEventListener('click',correctionPage);document.querySelector('#details').onclick=reviewPage;document.querySelector('#back').onclick=home}
async function settingsPage(){const enabled=await enabledPoints(),points=['相反数','绝对值','去括号','添括号','合并同类项','整式加减综合'];shell(`<section class="card"><p class="eyebrow">学习范围</p><h1 class="title">已学习的知识点</h1><p class="subtle">只影响未来日期的新任务。</p><div class="answer-area">${points.map(p=>`<label><input type="checkbox" value="${p}" ${enabled.includes(p)?'checked':''}> ${p}</label>`).join('')}</div><div class="actions"><button id="save-settings">保存设置</button><button class="secondary" id="cancel">返回</button></div></section>`);document.querySelector('#save-settings').onclick=async()=>{const v=[...document.querySelectorAll('input:checked')].map(x=>x.value);if(v.length){await saveSetting('enabledKnowledgePoints',v);home()}};document.querySelector('#cancel').onclick=home}
async function boot(){try{await openDB();const imported=await importQuestions({deferFixedQuestionSync:true});await runQuestionBankFixMigration(imported.incoming||[]);date=today();task=await getOrCreateToday();questions=await questionsFor(task);if(questions.length!==10)throw Error('今日任务生成失败');await restoreSubmittedCheckin();await home();initPwaUpdates()}catch(e){shell(`<section class="card"><h1>暂时无法启动</h1><p>${esc(e.message)}</p></section>`);console.error(e)}}boot();
