import {importQuestions,get,put,all,openDB,saveSetting} from './db.js';
import {today,getOrCreateToday,questionsFor,enabledPoints} from './questionEngine.js';
import {score} from './scoring.js';
import {recordWrong,recordCorrect} from './wrongQuestions.js';
import {updateKnowledge} from './statistics.js';
import {formatMath,normalizeMathInput,displayClass} from './formatMath.js';
const app=document.querySelector('#app');let task,questions,date,activeMathInput=null,lastMathSelection=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qAnswer=q=>Array.isArray(q.answer)?q.answer.join('；'):q.answer;
const answers=async()=> (await all('answers')).filter(x=>x.date===date);
const record=q=>get('answers',`${date}:${q.id}`);
function shell(html){app.innerHTML=`<div class="shell">${html}</div>`}
function unfinished(records){const done=new Set(records.filter(x=>x.resolved).map(x=>x.questionId));const saved=Number(task.currentIndex||0);return !done.has(task.questionIds[saved])?saved:task.questionIds.findIndex(id=>!done.has(id))}
async function home(){const rs=await answers(),done=rs.filter(x=>x.resolved).length,checkins=await all('checkins');const focus=[...new Set(questions.map(q=>q.knowledgePoint))].slice(0,3).join('、');shell(`<section class="card"><p class="eyebrow">七年级数学</p><h1 class="title">每日计算打卡</h1><p class="subtle">${date} · 基础诊断模式</p><div class="home-grid"><div class="metric">连续打卡<b>${checkins.length} 天</b></div><div class="metric">今日任务<b>${done} / 10</b></div><div class="metric">预计用时<b>8-10 分钟</b></div></div><p class="focus">今日重点：${esc(focus)}</p><button class="primary-wide" id="start">${done===10?'查看今日结果':done?'继续今日训练':'开始今日训练'}</button><div class="actions"><button class="secondary" id="settings">学习范围设置</button></div></section>`);document.querySelector('#start').onclick=()=>done===10?resultPage():questionPage(unfinished(rs));document.querySelector('#settings').onclick=settingsPage;}
function toolKeys(q){const basic=['−','/','(',')'];return q.answerType==='number'?basic:[...basic,'×','|','²','³']}
function inputTools(q){return `<div class="math-tools">${toolKeys(q).map(k=>`<button type="button" data-key="${k}">${k}</button>`).join('')}</div>`}
function bindTools(){const inputs=[...document.querySelectorAll('[data-answer]')];const remember=e=>{activeMathInput=e.currentTarget;lastMathSelection=activeMathInput.selectionStart??activeMathInput.value.length;};inputs.forEach(input=>['focus','click','keyup','select','input'].forEach(event=>input.addEventListener(event,remember)));document.querySelectorAll('[data-key]').forEach(button=>{const keepInputFocus=e=>e.preventDefault();button.addEventListener('pointerdown',keepInputFocus);button.addEventListener('mousedown',keepInputFocus);button.addEventListener('click',()=>{const input=activeMathInput&&document.contains(activeMathInput)?activeMathInput:inputs[0];if(!input)return;const start=input.selectionStart??lastMathSelection??input.value.length,end=input.selectionEnd??start,key=button.dataset.key;input.value=input.value.slice(0,start)+key+input.value.slice(end);const cursor=start+key.length;input.focus({preventScroll:true});input.setSelectionRange(cursor,cursor);lastMathSelection=cursor;input.dispatchEvent(new Event('input',{bubbles:true}));});});}
async function questionPage(index){const q=questions[index],old=await record(q);if(old?.resolved)return questionPage(unfinished(await answers()));task.currentIndex=index;await put('dailyTasks',task);const count=q.answerType==='multiple_blank'?(Array.isArray(q.answer)?q.answer.length:1):1;const inputs=Array.from({length:count},(_,i)=>`<input data-answer="${i}" inputmode="text" autocomplete="off" value="${esc(old?.currentInputs?.[i]||'')}" placeholder="答案${count>1?` ${i+1}`:''}">`).join('');const feedback=old?.feedback?`<div class="feedback ${old.feedback.kind}">${esc(old.feedback.text)}</div>${old.showAnswer?`<div class="answer-key">PDF 标准答案：${formatMath(qAnswer(q))}</div>`:''}`:'';shell(`<section class="card question-card"><div class="topline"><span>第 ${index+1} / 10 题</span><span class="tag">${esc(q.knowledgePoint)}</span></div><div class="progress"><i style="width:${index/10*100}%"></i></div><div class="question ${displayClass(q.question)}">${formatMath(q.displayQuestion||q.question)}</div><div class="answer-area">${inputs}</div>${inputTools(q)}${feedback}<div class="actions"><button id="submit">提交答案</button><button class="warning" id="giveup">不会</button>${index?'<button class="secondary" id="prev">上一题</button>':''}</div></section>`);bindTools();document.querySelector('#submit').onclick=()=>prepareSubmit(q,index);document.querySelector('#giveup').onclick=()=>giveUp(q,index);document.querySelector('#prev')?.addEventListener('click',()=>questionPage(index-1));}
function prepareSubmit(q,index){const values=[...document.querySelectorAll('[data-answer]')].map(x=>x.value.trim());const complex=['expression','fill_blank','multiple_blank','conditional_expression','ordered_terms'].includes(q.answerType);if(!complex)return submit(q,index,values);const read=values.map(normalizeMathInput).join('；'),area=document.querySelector('.actions');area.innerHTML=`<div class="answer-key">系统读取为：${esc(read)}</div><button id="confirm">确认提交</button><button class="secondary" id="edit">继续修改</button>`;document.querySelector('#confirm').onclick=()=>submit(q,index,values);document.querySelector('#edit').onclick=()=>questionPage(index);}
async function save(q,r){r.key=`${date}:${q.id}`;r.date=date;r.questionId=q.id;await put('answers',r)}
async function submit(q,index,values){let r=await record(q)||{attemptCount:0,startTime:Date.now(),firstWrongRecorded:false};r.currentInputs=values;const verdict=score(q,values);if(verdict.manualCheck){r.feedback={kind:'manual',text:'这个输入无法可靠解析，系统不会直接判错。请使用 +、−、×、÷、/、²、³、括号重新输入。'};await save(q,r);return questionPage(index)}r.attemptCount++;if(r.attemptCount===1){r.firstAnswer=values;r.firstAttemptCorrect=verdict.correct}if(verdict.correct){r.finalAnswer=values;r.corrected=!r.firstAttemptCorrect;r.resolved=true;r.endTime=Date.now();await save(q,r);await updateKnowledge(q,date,!!r.firstAttemptCorrect);if(!r.firstAttemptCorrect)await recordCorrect(q.id);const rs=await answers();if(rs.filter(x=>x.resolved).length===10){const first=rs.filter(x=>x.firstAttemptCorrect).length;await put('checkins',{date,completedAt:Date.now(),firstCorrect:first,wrong:10-first,corrected:rs.filter(x=>x.corrected).length});return resultPage()}return questionPage(unfinished(rs))}if(!r.firstWrongRecorded){r.firstWrongRecorded=true;r.firstAttemptCorrect=false;await recordWrong(q.id,date)}if(r.attemptCount===1)r.feedback={kind:'bad',text:'再检查一下符号和计算过程。'};else if(r.attemptCount===2)r.feedback={kind:'bad',text:'提示：先处理括号和正负号，再合并同类项。'};else{r.showAnswer=true;r.feedback={kind:'bad',text:'请参考 PDF 标准答案后重新输入，完成订正。'}}await save(q,r);questionPage(index)}
async function giveUp(q,index){let r=await record(q)||{attemptCount:0,startTime:Date.now(),firstWrongRecorded:false};if(!r.firstWrongRecorded){r.firstWrongRecorded=true;r.firstAttemptCorrect=false;await recordWrong(q.id,date)}r.gaveUp=true;r.attemptCount=Math.max(3,r.attemptCount);r.showAnswer=true;r.feedback={kind:'bad',text:'先看标准答案，再重新输入正确答案完成订正。'};await save(q,r);questionPage(index)}
async function resultPage(){const rs=await answers(),first=rs.filter(x=>x.firstAttemptCorrect).length,corrected=rs.filter(x=>x.corrected).length;const weak={};for(const r of rs)if(!r.firstAttemptCorrect){const q=questions.find(x=>x.id===r.questionId);weak[q.knowledgePoint]=(weak[q.knowledgePoint]||0)+1}shell(`<section class="card result"><p class="eyebrow">今日完成</p><h1 class="title">10 / 10</h1><div class="home-grid"><div class="metric">首次正确<b>${first} / 10</b></div><div class="metric">首次正确率<b>${first*10}%</b></div><div class="metric">已订正<b>${corrected} 题</b></div></div><p class="focus">今天需要多复习：${esc(Object.keys(weak).join('、')||'今天的基础很扎实')}</p><button class="primary-wide" id="back">返回首页</button></section>`);document.querySelector('#back').onclick=home}
async function settingsPage(){const enabled=await enabledPoints(),points=['相反数','绝对值','去括号','添括号','合并同类项','整式加减综合'];shell(`<section class="card"><p class="eyebrow">学习范围</p><h1 class="title">已学习的知识点</h1><p class="subtle">只影响未来日期的新任务。</p><div class="answer-area">${points.map(p=>`<label><input type="checkbox" value="${p}" ${enabled.includes(p)?'checked':''}> ${p}</label>`).join('')}</div><div class="actions"><button id="save-settings">保存设置</button><button class="secondary" id="cancel">返回</button></div></section>`);document.querySelector('#save-settings').onclick=async()=>{const v=[...document.querySelectorAll('input:checked')].map(x=>x.value);if(v.length){await saveSetting('enabledKnowledgePoints',v);home()}};document.querySelector('#cancel').onclick=home}
async function boot(){try{await openDB();await importQuestions();date=today();task=await getOrCreateToday();questions=await questionsFor(task);if(questions.length!==10)throw Error('今日任务生成失败');await home();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js')}catch(e){shell(`<section class="card"><h1>暂时无法启动</h1><p>${esc(e.message)}</p></section>`);console.error(e)}}boot();
