import {all,get,put,setting} from './db.js';
import {summarizeKnowledge} from './statistics.js';
import {KNOWLEDGE_POINTS,includeNewKnowledgePoints} from './knowledgePoints.js';
const hash=s=>[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,2166136261);
const daysAgo=(date,then)=>then?Math.max(0,Math.round((new Date(`${date}T00:00:00`)-new Date(`${then}T00:00:00`))/86400000)):9999;
export const POWER_BOOST_DAYS=14;
const POWER_BOOST_IDS=new Set(Array.from({length:20},(_,index)=>`Q${String(index+180).padStart(4,'0')}`));
const POWER_BOOST_HIGH_IDS=new Set(['Q0183','Q0184','Q0186','Q0189','Q0190','Q0191','Q0192','Q0194','Q0197','Q0198']);
export const powerBoostActive=(checkinCount,startCheckinCount)=>Number.isInteger(startCheckinCount)&&checkinCount>=startCheckinCount&&checkinCount-startCheckinCount<POWER_BOOST_DAYS;
export function powerBoostStatus(questionId,answers=[]){let streak=0;for(const record of answers.filter(item=>item.questionId===questionId).slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')))){if(record.firstAttemptCorrect===true)streak++;else if(record.firstAttemptCorrect===false)streak=0}return streak>=3?'excluded':streak>=2?'normal':'priority'}
export const today=()=>new Date().toLocaleDateString('en-CA');
export async function enabledPoints(){return includeNewKnowledgePoints(await setting('enabledKnowledgePoints',KNOWLEDGE_POINTS))}
function ordered(pool,date,history,seed){return pool.slice().sort((a,b)=>{const ah=history.get(a.id),bh=history.get(b.id),au=ah?0:1,bu=bh?0:1;if(au!==bu)return bu-au;const ad=daysAgo(date,ah?.lastShownDate),bd=daysAgo(date,bh?.lastShownDate);if(ad!==bd)return bd-ad;const ac=ah?.shownCount||0,bc=bh?.shownCount||0;if(ac!==bc)return ac-bc;return (hash(`${a.id}:${seed}`)%997)-(hash(`${b.id}:${seed}`)%997)})}
function choose(pool,used,date,history,seed){return ordered(pool.filter(q=>!used.has(q.id)),date,history,seed)[0]}
function add(out,q,sourceType,reason,used){if(!q)return false;out.push({questionId:q.id,sourceType,targetKnowledgePoint:q.knowledgePoint,selectionReason:reason});used.add(q.id);return true}
function stateMap(enabled,stats){const raw=new Map(stats.map(s=>[s.knowledgePoint,s]));return enabled.map(k=>summarizeKnowledge(raw.get(k)||{knowledgePoint:k})).sort((a,b)=>b.weaknessScore-a.weaknessScore||a.knowledgePoint.localeCompare(b.knowledgePoint))}
function selectAcross(out,questions,kps,count,sourceType,date,history,used,reasonFor,limit=3){const picked=new Map;for(const item of out)if(item.sourceType===sourceType)picked.set(item.targetKnowledgePoint,(picked.get(item.targetKnowledgePoint)||0)+1);let guard=0;while(out.length<count&&guard++<100){let added=false;for(const kp of kps){if(out.length===count)break;if((picked.get(kp.knowledgePoint)||0)>=limit)continue;const q=choose(questions.filter(x=>x.knowledgePoint===kp.knowledgePoint),used,date,history,`${sourceType}:${guard}:${kp.knowledgePoint}`);if(add(out,q,sourceType,reasonFor(kp,q),used)){picked.set(kp.knowledgePoint,(picked.get(kp.knowledgePoint)||0)+1);added=true}}if(!added)break}return out}
function unseenExposure(out,questions,states,date,history,used){const unseen=states.filter(state=>state.attempts===0).sort((a,b)=>a.knowledgePoint.localeCompare(b.knowledgePoint));for(const state of unseen){const question=choose(questions.filter(item=>item.knowledgePoint===state.knowledgePoint),used,date,history,`unseen:${state.knowledgePoint}`);if(add(out,question,'review','unseen_knowledge_exposure',used))return state.knowledgePoint}return null}
function normalFill(out,questions,kps,count,date,history,used){const start=out.length,preferred=kps.filter(x=>['mastered','mostly_mastered'].includes(x.state));const order=preferred.length?preferred:kps;let n=0;while(out.length<start+count&&n++<100){let added=false;for(const kp of order){if(out.length>=start+count)break;const q=choose(questions.filter(x=>x.knowledgePoint===kp.knowledgePoint),used,date,history,`review:${n}:${kp.knowledgePoint}`);if(q&&add(out,q,'review',`normal_review: ${kp.knowledgePoint} lastShown=${history.get(q.id)?.lastShownDate||'never'}`,used))added=true}if(!added)break}return out}
function selectPowerBoost(out,questions,count,date,history,used,answers){let selected=0;const base=questions.filter(question=>POWER_BOOST_IDS.has(question.id)&&powerBoostStatus(question.id,answers)!=='excluded'),groupFor=question=>powerBoostStatus(question.id,answers)==='priority'&&POWER_BOOST_HIGH_IDS.has(question.id)?'high':'ordinary';for(let slot=0;slot<count;slot++){const groups=slot%3!==1?['high','ordinary']:['ordinary','high'];let question;for(const allowRecent of [false,true]){for(const group of groups){const pool=base.filter(item=>groupFor(item)===group&&!used.has(item.id)&&(allowRecent||daysAgo(date,history.get(item.id)?.lastShownDate)>2));question=ordered(pool,date,history,`power_boost:${slot}:${group}`).at(0);if(question)break}if(question)break}if(!question)break;const tier=POWER_BOOST_HIGH_IDS.has(question.id)&&powerBoostStatus(question.id,answers)==='priority'?'高优先级':'普通';if(add(out,question,'review',`power_boost: 幂运算14日强化（${tier}·${question.subKnowledgePoint}）`,used))selected++}return selected}
export function buildAdaptiveTask({date,questions,enabled,checkins=[],stats=[],wrongQuestions=[],history=[],answers=[],powerBoost=false}){
  const bank=questions.filter(q=>enabled.includes(q.knowledgePoint)),historyMap=new Map(history.map(x=>[x.questionId,x])),states=stateMap(enabled,stats),used=new Set,items=[],diagnostic=checkins.length<5;
  if(diagnostic){
    if(powerBoost)selectPowerBoost(items,bank,3,date,historyMap,used,answers);
    let turn=0;
    while(items.length<10&&turn++<100){let added=false;for(const kp of states){if(items.length===10)break;const q=choose(bank.filter(x=>x.knowledgePoint===kp.knowledgePoint),used,date,historyMap,`diagnostic:${turn}:${kp.knowledgePoint}`);if(add(items,q,'review',`diagnostic: balanced coverage for ${kp.knowledgePoint}`,used))added=true}if(!added)break}
  }else{
    const due=wrongQuestions.filter(w=>!w.mastered&&w.nextReviewDate&&w.nextReviewDate<=date).map(w=>({w,q:bank.find(q=>q.id===w.questionId)})).filter(x=>x.q).sort((a,b)=>a.w.nextReviewDate.localeCompare(b.w.nextReviewDate)||b.w.wrongCount-a.wrongCount||b.w.lastWrongDate.localeCompare(a.w.lastWrongDate));
    for(const {w,q} of due.slice(0,2))add(items,q,'wrong_review',`wrong_review: reviewStage=${w.reviewStage}, due=${w.nextReviewDate}`,used);
    const ranked=states.filter(s=>s.state!=='insufficient_data').sort((a,b)=>b.weaknessScore-a.weaknessScore),weak=ranked.filter(s=>['priority_weak','weak'].includes(s.state)),focus=weak.length?weak:ranked.length?ranked:states,cap=focus.length===1?4:3;
    selectAcross(items,bank,focus,items.length+5,'weakness',date,historyMap,used,s=>`${s.state}: ${s.knowledgePoint} recentAccuracy=${Math.round(s.recentAccuracy)}%`,cap);
    if(items.filter(x=>x.sourceType==='weakness').length<5)selectAcross(items,bank,states,items.length+(5-items.filter(x=>x.sourceType==='weakness').length),'weakness',date,historyMap,used,s=>`relative_lowest: ${s.knowledgePoint} recentAccuracy=${Math.round(s.recentAccuracy)}%`,cap);
    const reviewCount=3+(2-due.slice(0,2).length),reviewStart=items.length,duePower=due.filter(item=>POWER_BOOST_IDS.has(item.q.id)).length,boostCount=powerBoost?Math.min(reviewCount,Math.max(0,3-Math.min(3,duePower))):0;
    selectPowerBoost(items,bank,boostCount,date,historyMap,used,answers);
    const exposed=reviewCount>(items.length-reviewStart)?unseenExposure(items,bank,states,date,historyMap,used):null;
    normalFill(items,bank,exposed?states.filter(state=>state.attempts>0):states,reviewCount-(items.length-reviewStart),date,historyMap,used);
  }
if(items.length<10){const fallback=ordered(bank.filter(q=>!used.has(q.id)),date,historyMap,'fallback');for(const q of fallback){if(items.length===10)break;add(items,q,'review',`normal_review: fallback ${q.knowledgePoint}`,used)}}return {date,questionIds:items.map(x=>x.questionId),items,createdAt:Date.now(),mode:diagnostic?'diagnosticPhase':'adaptive_5_3_2',selectionReason:Object.fromEntries(items.map(x=>[x.questionId,x.selectionReason]))}}
async function recordHistory(items,date){for(const item of items){const old=await get('questionHistory',item.questionId)||{questionId:item.questionId,shownCount:0,lastShownDate:null};old.shownCount++;old.lastShownDate=date;await put('questionHistory',old)}}
export async function getOrCreateToday(){const date=today(),existing=await get('dailyTasks',date);if(existing)return existing;const [questions,enabled,checkins,stats,wrongs,history,answers,startSetting]=await Promise.all([all('questions'),enabledPoints(),all('checkins'),all('knowledgeStats'),all('wrongQuestions'),all('questionHistory'),all('answers'),setting('powerBoostStartCheckinCount',null)]);const startCheckinCount=Number.isInteger(startSetting)?startSetting:checkins.length;if(!Number.isInteger(startSetting))await saveSetting('powerBoostStartCheckinCount',startCheckinCount);const task=buildAdaptiveTask({date,questions,enabled,checkins,stats,wrongQuestions:wrongs,history,answers,powerBoost:powerBoostActive(checkins.length,startCheckinCount)});await put('dailyTasks',task);await recordHistory(task.items,date);return task}
export async function questionsFor(task){const q=await all('questions'),m=new Map(q.map(x=>[x.id,x]));return task.questionIds.map(id=>{const item=m.get(id);return Array.isArray(item.answer)?{...item,answerType:'multiple_blank'}:item;});}
