import {normalizeMathInput} from './formatMath.js';
const clean=s=>normalizeMathInput(s).replace(/[\s，。；;]/g,'').replace(/[\[\{]/g,'(').replace(/[\]\}]/g,')');
function fraction(input){const raw=String(input??'').trim();const mixed=raw.match(/^([+-]?)(\d+)\s+(\d+)\/(\d+)$/);if(mixed){const v=Number(mixed[2])+Number(mixed[3])/Number(mixed[4]);return mixed[1]==='-'?-v:v}const s=clean(raw);if(!/^[-+]?(\d+(?:\.\d+)?|\d+\/\d+)$/.test(s))throw Error('not number');if(s.includes('/')){let[a,b]=s.split('/').map(Number);return a/b}return Number(s)}
function toks(s){const r=[];for(let i=0;i<s.length;){if(/\d|\./.test(s[i])){let j=i+1;while(/[\d.]/.test(s[j]))j++;r.push(['n',s.slice(i,j)]);i=j}else if(/[a-zA-Z]/.test(s[i])){r.push(['v',s[i].toLowerCase()]);i++}else if('+-*/^()'.includes(s[i]))r.push([s[i++]]);else throw Error('token')}return r}
const add=(a,b)=>{const o=new Map(a);for(const[k,v]of b)o.set(k,(o.get(k)||0)+v);return o},neg=a=>new Map([...a].map(([k,v])=>[k,-v])),mul=(a,b)=>{const o=new Map;for(const[ka,va]of a)for(const[kb,vb]of b){const e={};for(const k of (ka?ka.split('*'):[])){const[p,n='1']=k.split('^');e[p]=(e[p]||0)+Number(n)}for(const k of(kb?kb.split('*'):[])){const[p,n='1']=k.split('^');e[p]=(e[p]||0)+Number(n)}const key=Object.keys(e).sort().map(k=>e[k]===1?k:`${k}^${e[k]}`).join('*');o.set(key,(o.get(key)||0)+va*vb)}return o};
function poly(s){const t=toks(clean(s));let p=0,starts=()=>['n','v','('].includes(t[p]?.[0]);function e(){let a=m();while(['+','-'].includes(t[p]?.[0])){const op=t[p++][0],b=m();a=op==='+'?add(a,b):add(a,neg(b))}return a}function m(){let a=f();while(['*','/'].includes(t[p]?.[0])||starts()){const op=['*','/'].includes(t[p]?.[0])?t[p++][0]:'*',b=f();if(op==='/'){if(b.size!==1||!b.has(''))throw Error('symbol divide');a=new Map([...a].map(([k,v])=>[k,v/b.get('')]))}else a=mul(a,b)}return a}function f(){let sign=1;if(['+','-'].includes(t[p]?.[0]))sign=t[p++][0]==='-'?-1:1;let a;if(t[p]?.[0]==='n')a=new Map([['',Number(t[p++][1])]]);else if(t[p]?.[0]==='v')a=new Map([[t[p++][1],1]]);else if(t[p]?.[0]==='('){p++;a=e();if(t[p]?.[0]!==')')throw Error('bracket');p++}else throw Error('factor');if(t[p]?.[0]==='^'){let n=Number(t[++p][1]);p++;let x=new Map([['',1]]);while(n--)x=mul(x,a);a=x}return sign<0?neg(a):a}const out=e();if(p!==t.length)throw Error('tail');return out}
function same(a,b){const x=poly(a),y=poly(b),keys=new Set([...x.keys(),...y.keys()]);return [...keys].every(k=>Math.abs((x.get(k)||0)-(y.get(k)||0))<1e-9)}
function one(input,answer,type){try{if(type==='number')return {correct:Math.abs(fraction(input)-fraction(answer))<1e-10};if(type==='ordered_terms')return {correct:clean(input)===clean(answer)};return {correct:same(input,answer)}}catch{return {manualCheck:true,correct:false}}}
export function score(question,inputs){const type=question.answerType,ans=question.answer;if(type==='multiple_blank'||Array.isArray(ans)){const values=Array.isArray(ans)?ans:[ans];if(inputs.length!==values.length)return {correct:false};let manual=false;const ok=values.every((v,i)=>{const r=one(inputs[i],v,'expression');manual||=r.manualCheck;return r.correct});return manual&&!ok?{manualCheck:true,correct:false}:{correct:ok}}return one(inputs[0],ans,type)}
