(() => {
  const KEY = 'grade7-math-question-bank-review-v1'; let questions = []; let visible = []; let currentId = null;
  const $ = id => document.getElementById(id); const escape = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const save = () => { localStorage.setItem(KEY, JSON.stringify(questions)); $('storage-status').textContent = `已保存到此浏览器（${new Date().toLocaleTimeString()}）`; };
  const counts = () => questions.reduce((m,q)=>(m.total++,m[q.status]=(m[q.status]||0)+1,m),{total:0,pending:0,needsReview:0,approved:0,rejected:0});
  function download(name, value) { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([value],{type:'application/json;charset=utf-8'})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
  function filters(){ ['kp-filter','page-filter'].forEach((id,n)=>{const values=[...new Set(questions.map(q=>n?(q.questionPage||q.page):q.knowledgePoint))].sort(); $(id).innerHTML='<option value="all">全部</option>'+values.map(v=>`<option>${escape(v)}</option>`).join('');}); }
  function renderStats(){const c=counts(); $('stats').innerHTML=[['总题数','total'],['已确认','approved'],['待审核','pending'],['需要复核','needsReview'],['已排除','rejected']].map(([t,k])=>`<div class="stat"><span>${t}</span><strong>${c[k]||0}</strong></div>`).join('');}
  function apply(){const st=$('status-filter').value,kp=$('kp-filter').value,p=$('page-filter').value,q=$('query').value.trim().toLowerCase(); visible=questions.filter(x=>(st==='all'||x.status===st)&&(kp==='all'||x.knowledgePoint===kp)&&(p==='all'||String(x.questionPage||x.page)===p)&&(!q||x.id.toLowerCase().includes(q)||x.sourceIndex.toLowerCase().includes(q))); if(!visible.some(q=>q.id===currentId)) currentId=visible[0]?.id||null; renderList(); renderEditor();}
  function renderList(){$('list').innerHTML=visible.length?visible.map(q=>`<button class="item ${q.id===currentId?'active':''}" data-id="${q.id}"><b>${q.id}</b> <span class="badge ${q.status}">${q.status}</span><br><small>题目第${q.questionPage||q.page}页 · 答案第${q.answerPage||'—'}页 · ${escape(q.sourceIndex)}</small></button>`).join(''):'<p style="padding:16px">当前筛选没有需要人工处理的题目。</p>'; document.querySelectorAll('.item').forEach(b=>b.onclick=()=>{currentId=b.dataset.id;renderList();renderEditor();});}
  function field(label,key,wide=false,area=false){const q=questions.find(x=>x.id===currentId);const v=escape(Array.isArray(q[key])?q[key].join(' | '):q[key]||'');return `<label class="${wide?'wide':''}">${label}${area?`<textarea data-key="${key}">${v}</textarea>`:`<input data-key="${key}" value="${v}">`}</label>`;}
  function renderEditor(){const q=questions.find(x=>x.id===currentId);if(!q){$('editor').innerHTML='<div class="editor">请调整筛选条件；默认只显示 needsReview。</div>';return;} $('editor').innerHTML=`<div class="editor"><h2>${q.id}</h2><div class="meta"><span>PDF：${escape(q.source)}</span><span>题目页：${q.questionPage||q.page}</span><span>答案页：${q.answerPage||'—'}</span><span>原题号：${escape(q.sourceIndex)}</span><span>答案类型：${escape(q.answerType||'—')}</span><span>验算：${escape(q.answerCheck||'not_checked')}</span></div><div class="fields">${field('题目','question',true,true)}${field('标准答案（多空用 | 分隔）','answer',true,true)}${field('知识点','knowledgePoint')}${field('细分知识点','subKnowledgePoint')}${field('答案类型','answerType')}${field('验算结果','answerCheck')}${field('难度 1-5','difficulty')}${field('标签（逗号分隔）','tags')}${field('审核备注','reviewNote',true,true)}</div><div class="actions"><button data-status="approved">确认正确</button><button class="warn" data-status="needsReview">需要复核</button><button class="danger" data-status="rejected">不使用</button><button class="secondary" id="prev">上一题</button><button class="secondary" id="next">下一题</button></div></div>`; document.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{let v=el.value;if(el.dataset.key==='tags')v=v.split(',').map(x=>x.trim()).filter(Boolean);if(el.dataset.key==='answer'&&q.answerType==='multiple_blank')v=v.split('|').map(x=>x.trim());if(el.dataset.key==='difficulty')v=Math.min(5,Math.max(1,Number(v)||1));q[el.dataset.key]=v;save();renderStats();renderList();}); document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{q.status=b.dataset.status;save();renderStats();renderList();renderEditor();}); const move=d=>{let i=visible.findIndex(x=>x.id===currentId);currentId=visible[Math.max(0,Math.min(visible.length-1,i+d))]?.id;renderList();renderEditor();};$('prev').onclick=()=>move(-1);$('next').onclick=()=>move(1);}
  function exportSets(){const approved=questions.filter(q=>q.status==='approved'), rejected=questions.filter(q=>q.status==='rejected'), review=questions.filter(q=>q.status==='needsReview');download('questions.json',JSON.stringify(approved,null,2));download('questions_rejected.json',JSON.stringify(rejected,null,2));download('questions_needs_review.json',JSON.stringify(review,null,2));}
  function report(){const c=counts(), by={};questions.forEach(q=>by[q.knowledgePoint]=(by[q.knowledgePoint]||0)+1);let t='# 题库审核报告\n\n';t+=`- 总题数：${c.total}\n- approved：${c.approved||0}\n- pending：${c.pending||0}\n- needsReview：${c.needsReview||0}\n- rejected：${c.rejected||0}\n\n## 按知识点统计\n\n`;Object.entries(by).forEach(([k,v])=>t+=`- ${k}：${v}\n`);t+='\n## needsReview 题目\n\n';questions.filter(q=>q.status==='needsReview').forEach(q=>t+=`- ${q.id}｜第${q.page}页｜${q.sourceIndex}｜${q.reviewNote}\n`);download('review_report.md',t);}
  function start(){try{questions=JSON.parse(localStorage.getItem(KEY))||window.INITIAL_QUESTIONS; }catch{questions=window.INITIAL_QUESTIONS;} if(!Array.isArray(questions)||!questions.length)throw new Error('未找到初始题库数据');currentId=questions[0].id;filters();renderStats();apply();$('storage-status').textContent='初始题库已载入；所有修改会自动保存到此浏览器。'; ['status-filter','kp-filter','page-filter','query'].forEach(id=>$(id).oninput=apply);$('reset-filter').onclick=()=>{$('status-filter').value='all';$('kp-filter').value='all';$('page-filter').value='all';$('query').value='';apply();};$('backup').onclick=()=>download('questions_review_backup.json',JSON.stringify(questions,null,2));$('export').onclick=exportSets;$('report').onclick=report();}
  start();
})();
